site_name: Meu gov.br
theme:
    name: material
    favicon: Images/logo.png
    logo: Images/logo.png
    language: pt
    features:
        - navigation.tabs
        - header.autohide

extra:
    generator: false

hide:
    - toc

nav:
    - Home: index.md
    - Apresentações:
          - Apresentação 01: 'Apresentacao/apresentacao1.md'
          - Apresentação 02: 'Apresentacao/apresentacao2.md'
          - Apresentação 03: 'Apresentacao/apresentacao3.md'
          - Apresentacao 04: 'Apresentacao/apresentacao4.md'
          #  - Apresentacao 05: ''
          #  - Apresentacao 06: ''
    - Planejamento: 'Planejamento/Planejamento.md'
    - Pré-rastreabilidade: 'Pre-Rastreabilidade/Rich_Picture.md'
    - Elicitação:
          - Personas: 'Elicitacao/Personas.md'
          - Introspecção: 'Elicitacao/introspeccao.md'
          - Questionário: 'Elicitacao/questionario.md'
          - Storyboard: 'Elicitacao/storyboard.md'
          - Priorização:
                - First Things First: 'Elicitacao/Priorizacao/ftf.md'
                - MoSCoW: 'Elicitacao/Priorizacao/moscow.md'
    - Modelagem de Requisitos:
          - Casos de Uso: 'Modelagem_Requisitos/Casos_uso.md'
          - Cenários: 'Modelagem_Requisitos/Cenarios.md'
          - Especificação Suplementar: 'Modelagem_Requisitos/EspecificacaoSuplementar.md'
          - Léxicos: 'Modelagem_Requisitos/Léxicos.md'
    - Modelagem de Requisitos - Ágil:
          - Backlog: 'Modelagem_Requisitos/Backlog.md'
          - Histórias de Usuário: 'Modelagem_Requisitos/Historias_de_usuario.md'
          - NFR Framework: 'Modelagem_Requisitos/NFR.md'
    - Análise de Requisitos:
          - Validação:
                - Prototipagem: 'Analise_Requisitos/prototipagem.md'
          - Verificação:
                - Backlog: 'Analise_Requisitos/VeriBacklog.md'
                - Casos de Uso: 'Analise_Requisitos/VeriCasosUso.md'
                - Cenários: 'Analise_Requisitos/VeriCenarios.md'
                - Especificação Suplementar: 'Analise_Requisitos/VeriEspSuplementar.md'
                - First Things First: 'Analise_Requisitos/VeriFTF.md'
                - Histórias de Usuário: 'Analise_Requisitos/VeriHistorias.md'
                - Introspecção: 'Analise_Requisitos/VeriIntrospeccao.md'
                - Léxicos: 'Analise_Requisitos/VeriLexicos.md'
                - MoSCoW: 'Analise_Requisitos/VeriMosCow.md'
                - NFR Framework: 'Analise_Requisitos/VeriNFR.md'
                - Personas: 'Analise_Requisitos/VeriPersonas.md'
                - Pré-Rastreabilidade: 'Analise_Requisitos/VeriPreRastreabilidade.md'
                - Questionário: 'Analise_Requisitos/VeriQuestionario.md'
                - Storyboard: 'Analise_Requisitos/VeriStoryboard.md'
docs_dir: docs/
